apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
  labels:
    type: aws-ebs
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.storageCapacity }}
  accessModes:
    - {{ .Values.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolumeReclaimPolicy }}
  awsElasticBlockStore:
    volumeID: "vol-04d1e87e5d84b5942"  
    fsType: ext4  
